version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.2.3


jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn -B -Dskiptests clean package
      - run:
          name: Run tests
          command: mvn test
      - codecov/upload
      - codecov/upload:
          flags: -f target/site/jacoco/jacoco.xml
      - run:
          name: Checkstyle
          command: |
            mvn checkstyle:checkstyle
          when: always
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report/index.html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
        at: target/site/apidocs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config --global user.email "seb.guimety@gmail.com"
            git config --global user.name "SebastienGuimety"
      - add_ssh_keys:
          fingerprints:
            - "aa:13:a9:0c:97:9f:9b:eb:1b:f3:31:dc:75:9c:34:00"
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            rm -rf docs
            mkdir docs
            cp -r target/site/apidocs/* docs/
            gh-pages --dist docs


workflows:
  version: 2
  maven_test:
    jobs:
      - maven/test
  build:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build




