version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.2.3


jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn -B -Dskiptests clean package
      - run:
          name: Run tests
          command: mvn test
      - codecov/upload
      - codecov/upload:
          flags: -f target/site/jacoco/jacoco.xml
      - run:
          name: Checkstyle
          command: |
            mvn checkstyle:checkstyle
          when: always
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report/index.html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run:
          name: Build and test
          command: mvn clean verify
            - run:
                name: Generate Javadoc
                command: mvn javadoc:javadoc
            - run:
                name: Deploy Javadoc to GitHub Pages
                command: |
                  git config --global user.email "seb.guimety@gmail.com"
                  git config --global user.name "SebastienGuimety"
                  mkdir gh-pages
                  cp -r target/site/apidocs/* gh-pages/
                  cd gh-pages
                  git init
                  git remote add origin git@github.com:SebastienGuimety/ceri-m1-techniques-de-test.git
                  git checkout -b gh-pages
                  git add .
                  git commit -m "Deploy Javadoc to GitHub Pages"
                  git push --force origin gh-pages


workflows:
  version: 2
  maven_test:
    jobs:
      - maven/test
  build:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build




