version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.2.3


jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    executor: maven/default
    working_directory: ~/my-project

    steps:
      - checkout
      - run:
          name: Build project
          command: mvn -B -D skiptests clean install
      - run:
          name: Run tests
          command: mvn test
      - codecov/upload:
          flags: -f target/site/jacoco/jacoco.xml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


workflows:
  version: 2
  maven_test:
    jobs:
      - maven/test
  build:
    when:
      and:
        - equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - build




